import React from 'react';
import styled from 'styled-components';
import { BiCamera, BiWifi, BiUser } from 'react-icons/bi';
import { IoMdPhonePortrait, IoMdEye, IoIosBody, IoIosBulb } from 'react-icons/io';

const HomeContainer = styled.div`
  padding: 50px;

  @media (max-width: 768px) { /* Mobile devices */
    padding: 20px;
  }
`;

const Heading = styled.h1`
  font-size: 36px;
  color: #333;
  margin-bottom: 20px;

  @media (max-width: 768px) { /* Mobile devices */
    font-size: 24px;
  }
`;

const Subheading = styled.h2`
  font-size: 24px;
  color: #666;
  margin-bottom: 10px;

  @media (max-width: 768px) { /* Mobile devices */
    font-size: 20px;
  }
`;

const FeatureContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  margin-bottom: 30px;
`;

const FeatureItem = styled.div`
  width: 50%;
  padding: 20px;

  @media (max-width: 768px) { /* Mobile devices */
    width: 100%;
  }
`;

const FeatureIcon = styled.div`
  font-size: 48px;
  color: #666;
  margin-bottom: 10px;
`;

const FeatureText = styled.p`
  color: #666;
  line-height: 1.5;
`;

const ProductPage = () => {
  return (
    <HomeContainer>
      <Heading>Advanced Imaging Technology for Precise Assessments</Heading>
      <Subheading>See Every Detail with Clarity</Subheading>
      <FeatureContainer>
        <FeatureItem>
          <FeatureIcon><BiCamera /></FeatureIcon>
          <FeatureText>
            High-resolution 2.0-megapixel camera captures clear images of teeth and oral cavity
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoIosBulb /></FeatureIcon>
          <FeatureText>
            Six LED lights provide optimal illumination for accurate assessments
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><BiWifi /></FeatureIcon>
          <FeatureText>
            Wireless connectivity for hassle-free operation
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><BiUser /></FeatureIcon>
          <FeatureText>
            User-friendly design with a simple one-touch button
          </FeatureText>
        </FeatureItem>
      </FeatureContainer>
      <Subheading>Real-Time Monitoring for Proactive Dental Care</Subheading>
      <FeatureContainer>
        <FeatureItem>
          <FeatureIcon><IoMdPhonePortrait /></FeatureIcon>
          <FeatureText>
            Mobile app provides real-time feedback on a child's oral health status
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoMdEye /></FeatureIcon>
          <FeatureText>
            Instant visualization of dental condition for informed decision-making
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoIosBody /></FeatureIcon>
          <FeatureText>
            Interactive games, brushing techniques, and reminders for engaging oral care routines
          </FeatureText>
          </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoIosBulb /></FeatureIcon>
          <FeatureText>
            Personalized prompts and suggestions generated by advanced machine learning algorithms
          </FeatureText>
        </FeatureItem>
      </FeatureContainer>
      <Heading>Seamless Integration with Dental Practices</Heading>
      <Subheading>Empowering Dentists for Effective Treatment Plans</Subheading>
      <FeatureContainer>
        <FeatureItem>
          <FeatureIcon><BiUser /></FeatureIcon>
          <FeatureText>
            Essential information about a child's oral health at the dentist's fingertips
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoIosBulb /></FeatureIcon>
          <FeatureText>
            Tailored treatment plans based on accurate and comprehensive data
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><BiUser /></FeatureIcon>
          <FeatureText>
            Improved communication and collaboration between parents and dentists
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoIosBulb /></FeatureIcon>
          <FeatureText>
            Enhanced patient care and proactive preventive measures
          </FeatureText>
        </FeatureItem>
      </FeatureContainer>
      <Heading>Convenience and Efficiency in Dental Examinations</Heading>
      <Subheading>Wireless Design for Flexibility</Subheading>
      <FeatureContainer>
        <FeatureItem>
          <FeatureIcon><BiWifi /></FeatureIcon>
          <FeatureText>
            Operates wirelessly on a Wi-Fi network
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><BiUser /></FeatureIcon>
          <FeatureText>
            No cables or cords for unrestricted movement
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoIosBody /></FeatureIcon>
          <FeatureText>
            Convenient and flexible dental examinations
          </FeatureText>
        </FeatureItem>
      </FeatureContainer>
      <Subheading>Quick Charging and Long Working Time</Subheading>
      <FeatureContainer>
        <FeatureItem>
          <FeatureIcon><IoIosBulb /></FeatureIcon>
          <FeatureText>
            USB 2.0 charging cable for fast and efficient charging
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><IoMdEye /></FeatureIcon>
          <FeatureText>
            30 minutes of continuous working time on a full charge
          </FeatureText>
        </FeatureItem>
        <FeatureItem>
          <FeatureIcon><BiUser /></FeatureIcon>
          <FeatureText>
            Uninterrupted dental examinations for seamless patient care
          </FeatureText>
        </FeatureItem>
      </FeatureContainer>
    </HomeContainer>
  );
};

export default ProductPage;

